[LABELS]
id = "1aS989ZLnzw9vjridv9fEzBAIvEBZ7NfO"

[KM_C_FEATURES]
id = "1Fo0yowSOffBqqYSvaUvzR4dWPeQQBwLU"

[KM_D_FEATURES]
id = "1zpXZjKY002bPK0JBp9_2U0S8OeqppDqK"

[KM_V_FEATURES]
id = "1z1DbK1l5zmCl4c0JsiA3-Fwz6DgsZ-9L"

[PCA_C_FEATURES]
id = "1FFhttv6Gsp4p_Gr8l112Gre3_Q5OHMp_"

[PCA_D_FEATURES]
id = "1fPuO1NnFMK3PiP3sGXvUNppMtEdNDEhR"

[PCA_V_FEATURES]
id = "1KajcCmp4ZpIBUS2yTyyE85r5SrljnL1z"

[MODEL]
id = "16YO_aMvIP-SYYv-AboQZyKE_fsjEooV1"



